'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { Camera, Check, ChevronLeft, Download, Expand, Mail, QrCode, RefreshCcw, Sparkles, SwitchCamera, WandSparkles, X } from 'lucide-react';
import QRCode from 'qrcode';
import { useCallback, useEffect, useRef, useState } from 'react';
import { CatalogItem, CreationMode, styles, templates } from '@/lib/catalog';

type Step = 'welcome'|'email'|'style'|'camera'|'review'|'processing'|'result';
type CameraState = 'idle'|'loading'|'ready'|'denied'|'unavailable';

const processingStages = ['Preparing portrait','Analysing lighting','Applying selected style','Rendering final details','Preparing delivery'];
const promptIdeas = ['A desert explorer at golden hour','A celestial royal portrait','A futuristic scientist in a holographic lab'];
const badWords = ['nude','naked','sexual','gore','blood'];

function makeMockArtwork(source: string, accent: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = 1200; canvas.height = 1600;
      const ctx = canvas.getContext('2d');
      if (!ctx) return reject(new Error('Canvas unavailable'));
      const scale = Math.max(canvas.width / image.width, canvas.height / image.height);
      const w = image.width * scale, h = image.height * scale;
      ctx.filter = 'contrast(1.12) saturate(1.3)';
      ctx.drawImage(image, (canvas.width-w)/2, (canvas.height-h)/2, w, h);
      ctx.filter = 'none';
      const gradient = ctx.createLinearGradient(0,0,canvas.width,canvas.height);
      gradient.addColorStop(0,'rgba(34,211,238,.22)');
      gradient.addColorStop(.55,'rgba(0,0,0,0)');
      gradient.addColorStop(1,'rgba(124,58,237,.3)');
      ctx.fillStyle=gradient; ctx.fillRect(0,0,canvas.width,canvas.height);
      ctx.strokeStyle=accent; ctx.lineWidth=18; ctx.strokeRect(24,24,canvas.width-48,canvas.height-48);
      resolve(canvas.toDataURL('image/jpeg',.9));
    };
    image.onerror = reject; image.src = source;
  });
}

export default function Home() {
  const [step,setStep]=useState<Step>('welcome');
  const [email,setEmail]=useState(''); const [consent,setConsent]=useState(false); const [error,setError]=useState('');
  const [mode,setMode]=useState<CreationMode>('style'); const [selected,setSelected]=useState<CatalogItem>(styles[0]);
  const [prompt,setPrompt]=useState(''); const [cameraState,setCameraState]=useState<CameraState>('idle');
  const [facing,setFacing]=useState<'user'|'environment'>('user'); const [photo,setPhoto]=useState(''); const [result,setResult]=useState('');
  const [countdown,setCountdown]=useState(0); const [flash,setFlash]=useState(false); const [progress,setProgress]=useState(0);
  const [stage,setStage]=useState(0); const [busy,setBusy]=useState(false); const [split,setSplit]=useState(50); const [qr,setQr]=useState('');
  const [sent,setSent]=useState(false); const [showQr,setShowQr]=useState(false); const [lastActivity,setLastActivity]=useState(Date.now());
  const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const abortRef=useRef<AbortController|null>(null);

  const stopCamera=useCallback(()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current) videoRef.current.srcObject=null;setCameraState('idle')},[]);
  const restart=useCallback(()=>{stopCamera();abortRef.current?.abort();setStep('welcome');setEmail('');setConsent(false);setMode('style');setSelected(styles[0]);setPrompt('');setPhoto('');setResult('');setQr('');setSent(false);setShowQr(false);setBusy(false);setError('')},[stopCamera]);

  useEffect(()=>{const mark=()=>setLastActivity(Date.now());window.addEventListener('pointerdown',mark);window.addEventListener('keydown',mark);const timer=setInterval(()=>{if(step!=='welcome'&&Date.now()-lastActivity>90000)restart()},5000);return()=>{clearInterval(timer);window.removeEventListener('pointerdown',mark);window.removeEventListener('keydown',mark)}},[lastActivity,restart,step]);
  useEffect(()=>()=>stopCamera(),[stopCamera]);

  async function startCamera(){stopCamera();setCameraState('loading');setError('');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing,width:{ideal:1200},height:{ideal:1600}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraState('ready')}catch(err){const denied=err instanceof DOMException&&['NotAllowedError','SecurityError'].includes(err.name);setCameraState(denied?'denied':'unavailable')}}
  async function switchCamera(){setFacing(v=>v==='user'?'environment':'user');setTimeout(startCamera,20)}
  function doCapture(){const video=videoRef.current;if(!video)return;const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1200;const ctx=canvas.getContext('2d');if(!ctx)return;if(facing==='user'){ctx.translate(canvas.width,0);ctx.scale(-1,1)}const scale=Math.max(canvas.width/video.videoWidth,canvas.height/video.videoHeight);ctx.drawImage(video,(canvas.width-video.videoWidth*scale)/2,(canvas.height-video.videoHeight*scale)/2,video.videoWidth*scale,video.videoHeight*scale);setFlash(true);setTimeout(()=>setFlash(false),450);setPhoto(canvas.toDataURL('image/jpeg',.86));stopCamera()}
  function capture(){setCountdown(3);let n=3;const timer=setInterval(()=>{n--;setCountdown(n);if(n<=0){clearInterval(timer);doCapture()}},1000)}
  function validateEmail(){if(email&&!/^\S+@\S+\.\S+$/.test(email)){setError('Please enter a valid email address.');return false}if(!consent){setError('Please confirm the privacy consent to continue.');return false}setError('');return true}
  function chooseMode(next:CreationMode){setMode(next);if(next==='style')setSelected(styles[0]);if(next==='template')setSelected(templates[0])}

  async function generate(){if(!photo||busy)return;if(mode==='prompt'&&(!prompt.trim()||badWords.some(w=>prompt.toLowerCase().includes(w)))){setError('Please use a safe, descriptive portrait prompt.');return}setBusy(true);setStep('processing');setProgress(5);setStage(0);const controller=new AbortController();abortRef.current=controller;const timer=setInterval(()=>setProgress(p=>Math.min(92,p+Math.random()*8)),550);const stageTimer=setInterval(()=>setStage(s=>Math.min(4,s+1)),1500);try{const mock=await makeMockArtwork(photo,mode==='template'?'#c4b5fd':'#67e8f9');const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({image:mock,styleId:mode==='style'?selected.id:null,templateId:mode==='template'?selected.id:null,customPrompt:mode==='prompt'?prompt:null,email,sessionId:crypto.randomUUID()})});if(!response.ok)throw new Error('Generation failed');const data=await response.json();setProgress(100);setStage(4);setResult(data.resultUrl);const url=`${location.origin}/?result=${encodeURIComponent(data.token)}`;setQr(await QRCode.toDataURL(url,{width:440,margin:1}));setTimeout(()=>setStep('result'),650)}catch(e){if((e as Error).name!=='AbortError'){setError('The portrait could not be generated. Please retry or use demo mode.');setStep('review')}}finally{clearInterval(timer);clearInterval(stageTimer);setBusy(false)}}
  async function sendEmail(){if(!email){setError('No email was entered. Use the QR code or download instead.');return}setBusy(true);const response=await fetch('/api/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,image:result,exhibition:process.env.NEXT_PUBLIC_EXHIBITION_NAME||'AI Portrait Exhibition'})});setBusy(false);if(response.ok)setSent(true);else setError('Email delivery failed. The image is still available to download.')}
  function download(){const a=document.createElement('a');a.href=result;a.download='ai-exhibition-portrait.jpg';a.click()}
  function fullscreen(){document.documentElement.requestFullscreen?.()}

  const transition={initial:{opacity:0,y:18,scale:.985},animate:{opacity:1,y:0,scale:1},exit:{opacity:0,y:-14,scale:.99},transition:{duration:.32}};
  const header=(back?:()=>void)=><div className="button-row" style={{marginBottom:'1rem'}}>{back&&<button className="ghost-button" onClick={back}><ChevronLeft size={19}/> Back</button>}<button className="ghost-button" onClick={restart}><RefreshCcw size={18}/> Restart</button></div>;

  return <main className="app-shell"><div className="particles"/><header className="topbar"><div className="brand"><span className="brand-mark"><Sparkles/></span><span>PORTRAIT/AI</span></div><button className="ghost-button" onClick={fullscreen} aria-label="Enter fullscreen"><Expand size={19}/></button></header><section className="experience"><AnimatePresence mode="wait">
    {step==='welcome'&&<motion.div key="welcome" className="panel hero" {...transition}><div className="hero-layout"><div><span className="eyebrow"><WandSparkles size={14}/> Exhibition experience</span><h1>Transform Your <span className="gradient-text">Portrait with AI</span></h1><p className="subtitle">Take one photo. Choose a creative world. Receive an exhibition-ready portrait in moments.</p><button className="primary-button" style={{marginTop:'1.5rem',minWidth:220}} onClick={()=>setStep('email')}>Start Experience</button><p className="privacy-note">Your photo is used only to create your portrait and is automatically removed after the configured temporary period.</p></div><div className="hero-art" aria-hidden><div className="hero-art-inner"/></div></div></motion.div>}
    {step==='email'&&<motion.div key="email" className="panel" {...transition}>{header(()=>setStep('welcome'))}<span className="eyebrow">Step 1 · Delivery</span><h2 className="screen-title">Where should we send your masterpiece?</h2><div className="stack"><label className="field-label" htmlFor="email">Email address <span style={{color:'#94a3b8'}}>(optional with QR)</span></label><input id="email" className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/><label className="checkbox-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I consent to temporary processing of this photo and confirm I have permission to photograph the person shown.</span></label>{error&&<p className="error">{error}</p>}<button className="primary-button" onClick={()=>{if(validateEmail())setStep('style')}}>Continue</button></div></motion.div>}
    {step==='style'&&<motion.div key="style" className="panel" {...transition}>{header(()=>setStep('email'))}<span className="eyebrow">Step 2 · Create</span><h2 className="screen-title">Choose your transformation</h2><div className="mode-tabs">{(['style','template','prompt'] as CreationMode[]).map(m=><button key={m} className={`mode-tab ${mode===m?'active':''}`} onClick={()=>chooseMode(m)}>{m==='style'?'Art Styles':m==='template'?'Templates':'Custom Prompt'}</button>)}</div>{mode!=='prompt'?<div className="catalog-grid">{(mode==='style'?styles:templates).map(item=><button key={item.id} className={`catalog-card ${selected.id===item.id?'selected':''}`} onClick={()=>setSelected(item)}><span className="catalog-emoji">{item.emoji}</span><h3>{item.title}</h3><p>{item.description}</p></button>)}</div>:<div className="stack"><textarea className="textarea" maxLength={280} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the portrait you imagine..."/><div style={{display:'flex',justifyContent:'space-between',color:'#94a3b8'}}><span>{prompt.length}/280</span><button className="chip" onClick={()=>setPrompt(promptIdeas[Math.floor(Math.random()*promptIdeas.length)])}>Surprise Me</button></div><div className="suggestions">{promptIdeas.map(p=><button className="chip" key={p} onClick={()=>setPrompt(p)}>{p}</button>)}</div></div>}{error&&<p className="error">{error}</p>}<button className="primary-button" style={{width:'100%',marginTop:'1rem'}} onClick={()=>{setError('');setStep('camera')}}>Continue to Camera</button></motion.div>}
    {step==='camera'&&<motion.div key="camera" className="panel" {...transition}>{header(()=>{stopCamera();setStep('style')})}<span className="eyebrow">Step 3 · Camera</span><h2 className="screen-title">Centre your face</h2><div className="camera-stage">{cameraState==='ready'&&<video ref={videoRef} playsInline muted className={facing==='user'?'mirror':''}/>} {cameraState!=='ready'&&<div style={{height:'100%',display:'grid',placeItems:'center',padding:'2rem',textAlign:'center'}}><div><Camera size={55}/><h3>{cameraState==='loading'?'Starting camera…':cameraState==='denied'?'Camera permission denied':cameraState==='unavailable'?'Camera unavailable':'Camera is off'}</h3><p style={{color:'#94a3b8'}}>Use a well-lit space and hold the device at eye level.</p><button className="primary-button" onClick={startCamera}>{cameraState==='idle'?'Open Camera':'Try Again'}</button></div></div>}{cameraState==='ready'&&<><div className="portrait-guide"/><span className="camera-status">Centre your face · Look at the lens</span></>}{countdown>0&&<div className="countdown">{countdown}</div>}{flash&&<div className="flash"/>}</div>{cameraState==='ready'&&<><div className="capture-wrap"><button className="capture-button" onClick={capture} aria-label="Take photo"/></div><button className="secondary-button" style={{width:'100%'}} onClick={switchCamera}><SwitchCamera size={18}/> Switch Camera</button></>}</motion.div>}
    {step==='review'&&<motion.div key="review" className="panel" {...transition}>{header(()=>setStep('camera'))}<span className="eyebrow">Step 4 · Review</span><h2 className="screen-title">Ready to create?</h2><div className="review-grid"><div className="photo-card"><img src={photo} alt="Captured portrait"/></div><div className="summary-card"><h3>{mode==='prompt'?'Custom creation':selected.title}</h3><p>{mode==='prompt'?prompt:selected.description}</p><p>For best results, make sure the face is clear, centred and well lit.</p><div className="stack"><button className="secondary-button" onClick={()=>{setPhoto('');setStep('camera')}}>Retake Photo</button><button className="secondary-button" onClick={()=>setStep('style')}>Change Style</button><button className="primary-button" onClick={generate}>Generate Portrait</button></div></div></div>{error&&<p className="error">{error}</p>}</motion.div>}
    {step==='processing'&&<motion.div key="processing" className="panel processing" {...transition}><span className="eyebrow">Creating responsibly</span><h2 className="screen-title" style={{marginInline:'auto'}}>Your portrait is coming to life</h2><div className="processing-frame"><img src={photo} alt="Original portrait being processed"/><div className="scanline"/></div><div className="progress-track"><div className="progress-bar" style={{width:`${progress}%`}}/></div><div className="stage-list">{processingStages.map((s,i)=><div className={`stage-item ${i<=stage?'active':''}`} key={s}><span className="stage-dot"/>{i<stage?<Check size={17}/>:null}{s}</div>)}</div><p className="privacy-note">AI models learn visual patterns; they do not understand a person the way humans do.</p><button className="danger-button" onClick={()=>{abortRef.current?.abort();setStep('review')}}><X size={18}/> Cancel</button></motion.div>}
    {step==='result'&&<motion.div key="result" className="panel" {...transition}>{header()}<span className="eyebrow">Portrait complete</span><h2 className="screen-title">Meet your transformed self</h2><div className="compare" style={{'--split':`${split}%`} as React.CSSProperties}><img src={result} alt="Generated portrait"/><img className="compare-after" src={photo} alt="Original portrait"/><div className="compare-line"/><input aria-label="Before and after comparison" type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))}/></div>{sent&&<p className="success">✓ Your portrait has been sent successfully.</p>}{error&&<p className="error">{error}</p>}{showQr&&qr&&<div className="qr-box"><img src={qr} alt="QR code for temporary portrait link"/></div>}<div className="result-actions"><button className="primary-button" disabled={busy} onClick={sendEmail}><Mail size={18}/> Email Image</button><button className="secondary-button" onClick={()=>setShowQr(v=>!v)}><QrCode size={18}/> {showQr?'Hide':'Show'} QR Code</button><button className="secondary-button" onClick={download}><Download size={18}/> Download</button><button className="secondary-button" onClick={()=>{setStep('style');setResult('')}}><WandSparkles size={18}/> Try Another Style</button><button className="primary-button" onClick={restart}><RefreshCcw size={18}/> Create Another</button></div><p className="privacy-note">This experience automatically resets after 90 seconds of inactivity.</p></motion.div>}
  </AnimatePresence></section></main>;
}
